// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFjWEzIQkuH4SVY0C_MNDNOL3P8i639RE',
    appId: '1:838742603274:web:25cb22ea932bc1288451f3',
    messagingSenderId: '838742603274',
    projectId: 'notesnest-76bfb',
    authDomain: 'notesnest-76bfb.firebaseapp.com',
    storageBucket: 'notesnest-76bfb.firebasestorage.app',
    measurementId: 'G-MBGND2725R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPd5nVqTPp8b3IdQ8ovd7h62UuOxdQwHc',
    appId: '1:838742603274:android:1fe1f7b57a9319d48451f3',
    messagingSenderId: '838742603274',
    projectId: 'notesnest-76bfb',
    storageBucket: 'notesnest-76bfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIZ4hRUMywEKum-G4-_pEx8XfRtjpisnk',
    appId: '1:838742603274:ios:7318f5c5d87962518451f3',
    messagingSenderId: '838742603274',
    projectId: 'notesnest-76bfb',
    storageBucket: 'notesnest-76bfb.firebasestorage.app',
    iosBundleId: 'com.example.productCartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIZ4hRUMywEKum-G4-_pEx8XfRtjpisnk',
    appId: '1:838742603274:ios:7318f5c5d87962518451f3',
    messagingSenderId: '838742603274',
    projectId: 'notesnest-76bfb',
    storageBucket: 'notesnest-76bfb.firebasestorage.app',
    iosBundleId: 'com.example.productCartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFjWEzIQkuH4SVY0C_MNDNOL3P8i639RE',
    appId: '1:838742603274:web:11ac741fa65c0b028451f3',
    messagingSenderId: '838742603274',
    projectId: 'notesnest-76bfb',
    authDomain: 'notesnest-76bfb.firebaseapp.com',
    storageBucket: 'notesnest-76bfb.firebasestorage.app',
    measurementId: 'G-R6P2H17PZF',
  );
}
